@isTest
public class GetLocation_test {
 
    static testMethod void Eventlocationtest(){
        
        /*Account testenq = new Account(First_Name__c = 'test',Last_Name__c = 'enquiry',Mobile_1__c = '9876543210',Email__c = 'test@testmail.com');
        insert testenq;
        
        Event testevent = new Event(ActivityDate = date.today(),StartDateTime = System.Now(),EndDateTime = System.Now() + 1,WhatId = testenq.Id);
        insert testevent;
        
        System.Test.startTest();
        GetLocation.startLocation(34.234,34.23,testevent.id,'Event');
        GetLocation.endLocation(34.234,34.23,testevent.id,'Event');  
        System.Test.stopTest();*/
    }
   
}